#!/usr/bin/env node

import {writeFile} from "node:fs/promises";
import {dirname, resolve} from "node:path";
import {fileURLToPath, pathToFileURL} from "node:url";

const SOURCEAUDIO_ORIGIN = "https://jaxxslade.sourceaudio.com";
const DEFAULT_PLAYLIST_NAME = "JXS Selects";
const PUBLIC_PLAYLIST_NAME = "The Jaxx Slade Jukebox";

const cleanName = value => String(value || "")
  .replace(/\s*\(\d+\)\s*$/, "")
  .trim()
  .toLowerCase();

const asArray = value => Array.isArray(value) ? value : [];

export function findPlaylist(payload, wantedId, wantedName = DEFAULT_PLAYLIST_NAME) {
  const playlists = asArray(payload?.playlists || payload?.data?.playlists || payload?.data || payload);
  if (wantedId) {
    const byId = playlists.find(item => String(item?.id) === String(wantedId));
    if (byId) return byId;
  }

  const names = new Set([cleanName(wantedName), cleanName(PUBLIC_PLAYLIST_NAME)]);
  return playlists.find(item => names.has(cleanName(item?.name))) || null;
}

function playlistObject(payload) {
  return payload?.playlist || payload?.data?.playlist || payload?.data || payload;
}

function trackId(track) {
  return track?.id ?? track?.trackId ?? track?.track_id ?? track?.sourceAudioId ??
    track?.sourceaudio_id ?? track?.["SourceAudio ID"];
}

function trackTitle(track) {
  return track?.title ?? track?.name ?? track?.trackTitle ?? track?.track_title ??
    track?.["Title"] ?? track?.metadata?.Title ?? track?.metadata?.title;
}

export function playlistTracks(payload) {
  const playlist = playlistObject(payload);
  const tracks = asArray(playlist?.tracks || playlist?.items?.tracks || playlist?.items)
    .filter(item => trackId(item) !== undefined && trackId(item) !== null);

  return tracks.map((track, index) => {
    const id = trackId(track);
    const title = String(trackTitle(track) || "").trim();
    if (!title) throw new Error(`Playlist track ${index + 1} (${id}) has no title.`);
    return {id: String(id), title};
  });
}

export function extractEmbedCode(payload) {
  const text = typeof payload === "string" ? payload : JSON.stringify(payload);
  const match = text.match(/[?&]code=([a-f0-9]{20,})/i) || text.match(/\b([a-f0-9]{30,})\b/i);
  if (!match) throw new Error("SourceAudio did not return a track embed code.");
  return match[1];
}

export function renderJukeboxFile(playlist, tracks) {
  const publicMeta = {
    name: PUBLIC_PLAYLIST_NAME,
    sourceName: playlist.name,
    sourceId: playlist.id
  };
  const publicTracks = tracks.map(track => ({t: track.title, c: track.code}));

  return `/* Auto-generated by scripts/sync-jukebox.mjs. Public embed codes only. */\n` +
    `window.JUKEBOX_PLAYLIST = Object.freeze(${JSON.stringify(publicMeta, null, 2)});\n\n` +
    `window.JUKEBOX_TRACKS = Object.freeze(${JSON.stringify(publicTracks, null, 2)}.map(Object.freeze));\n`;
}

async function request(pathname, params, token) {
  const url = new URL(pathname, SOURCEAUDIO_ORIGIN);
  Object.entries({...params, token}).forEach(([key, value]) => {
    if (value !== undefined && value !== null && String(value) !== "") {
      url.searchParams.set(key, String(value));
    }
  });

  const response = await fetch(url, {headers: {accept: "application/json"}});
  const body = await response.text();
  let payload;
  try {
    payload = JSON.parse(body);
  } catch {
    payload = body;
  }

  if (!response.ok) throw new Error(`SourceAudio ${pathname} failed with HTTP ${response.status}.`);
  if (payload?.error) throw new Error(`SourceAudio ${pathname}: ${payload.error}`);
  return payload;
}

export async function syncJukebox({token, playlistId, playlistName, outputPath}) {
  if (!token) {
    throw new Error("SOURCEAUDIO_API_TOKEN is required. Store it as a GitHub Actions repository secret; never commit it.");
  }

  const published = await request("/api/playlists/getPublished", {}, token);
  const playlist = findPlaylist(published, playlistId, playlistName);
  if (!playlist) {
    throw new Error(`Published SourceAudio playlist not found: ${playlistName}. Publish it or set SOURCEAUDIO_JUKEBOX_PLAYLIST_ID.`);
  }

  const detail = await request("/api/playlists/getById", {playlist_id: playlist.id}, token);
  const tracks = playlistTracks(detail);
  if (!tracks.length) throw new Error(`SourceAudio playlist ${playlist.name} has no tracks.`);

  const synced = await Promise.all(tracks.map(async track => ({
    ...track,
    code: extractEmbedCode(await request("/api/tracks/getEmbedCode", {track_id: track.id}, token))
  })));

  await writeFile(outputPath, renderJukeboxFile(playlist, synced), "utf8");
  process.stdout.write(`Synced ${synced.length} tracks from "${playlist.name}".\n`);
}

const isDirectRun = process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href;
if (isDirectRun) {
  const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  syncJukebox({
    token: process.env.SOURCEAUDIO_API_TOKEN?.trim(),
    playlistId: process.env.SOURCEAUDIO_JUKEBOX_PLAYLIST_ID?.trim(),
    playlistName: process.env.SOURCEAUDIO_JUKEBOX_PLAYLIST_NAME?.trim() || DEFAULT_PLAYLIST_NAME,
    outputPath: resolve(repoRoot, "jukebox_tracks.js")
  }).catch(error => {
    process.stderr.write(`Jukebox sync failed: ${error.message}\n`);
    process.exitCode = 1;
  });
}
